basePath: /
host: lubisapp.herokuapp.com
info:
  contact:
    email: 1214040@std.ulbi.ac.id
    name: API Support
    url: https://github.com/MarlinaLubis
  description: This is a sample server.
  title: TES SWAG
  version: "1.0"
paths: {}
schemes:
- https
- http
swagger: "2.0"
